
export default {
	login : 'Login',
	register : 'Register',
	or_login_with: 'Or login with',
	or_register_with: 'Or register with',
	english: 'English',
	about: 'About Us',
	help: 'Help',
	trade: 'Trade',
	com_make_dif: 'Community Make Difference',
	trade_with: 'Trade with peoples accross the world.',
	help_each: 'Help each other with trading.',
	i_need: 'I Need',
	you_have_to_transfer: 'You Have to transfer',
	get_start: 'get start',
	best_way: 'The best way to start trading',
	trading_currency: 'Trading currency on anywhere with anyone',
	select_trader: 'Select trader below and start to trade..',
	hours_ago: 'hours ago',
	need: 'Need',
	can_give: 'Can give',
	trader: 'Trader',
	select: 'Select',
	no_post_match: 'No post match your needs , why don\'t create your own ?',
	create_post: 'Create Post',
	will_trade_with: 'You will trade with ..',
	will_get: 'You Will Get',	
	kotuka_fee: 'Kotuka fee',
	fee_percent: '0.5% amount that\'s converted + £1',
	lets_start: 'Let\'s start the trade with registration',
	your_email: 'Your email address',
	email_address: 'Email address',
	password: 'Password',
	google: 'Google',
	facebook: 'Facebook',
	sent_confirm: 'We\'ve sent you email confirmation',
	to_log_in: 'To log in, you need to confirm your email. Check your mail',
	we_sent: 'We\'ve sent you a link to confirm your email. Simply click the link and you\'re ready.',
	cp_right: 'Copyright @ Kotuka 2018',
	need_help: 'Need Help ?',
	post: 'Post',
	transaction: 'Transaction',
	recipient: 'Recipient',
	lets_complete_your_profile: 'Let\'s complete your profile..',
	first_n_midle_name: 'First & Middle Name',
	last_name: 'Last Name',
	phone: 'Phone Number',
	birthdate: 'Birthdate',
	address: 'Address',
	you_are_trading : 'You are trading with',
	purpose : 'Purpose',
	review: 'Review',
	transfer_process: 'Transfer Process',
	cancel: 'cancel',
	add: 'add',
	edit: 'edit',
	add_new_recipient_account: 'Add new recipient account',
	bank_account: 'Bank account',
	sort_code: 'Sort Code',
	country: 'Country',
	other: 'Other',
	question: 'Question',
	send: 'Send',
	fast: 'Fast',
	tolerable: 'Tolerable',
	fair: 'Fair',
	remove: 'Remove',
	transaction_status: 'Transaction Status',
	you: 'You',
	pay_now: 'Pay Now',
	search_again: 'Search Again',
	search: 'Search',
	no_post: 'There\'s no post yet , why don\'t create your own ?',
	prev: 'Prev',
	next: 'Next',
	account_no: 'Account Number',
	description: 'Description'	
}

