
export default {
	login : 'Login',
	register : 'Register',
	or_login_with: 'Or login with',
	or_register_with: 'Or register with',
	english: 'English',
	about: 'About Us',
	help: 'Help',
	trade: 'Trade',
	com_make_dif: 'Community Make Difference',
	trade_with: 'Trade with peoples accross the world.',
	help_each: 'Help each other with trading.',
	i_need: 'I Need',
	you_have_to_transfer: 'You Have to transfer',
	get_start: 'get start',
	best_way: 'The best way to start trading',
	trading_currency: 'Trading currency on anywhere with anyone',
	select_trader: 'Select trader below and start to trade..',
	hours_ago: 'hours ago',
	need: 'Need',
	can_give: 'Can give',
	trader: 'Trader',
	select: 'Select',
	no_post_match: 'No post match your needs , why don\'t create your own ?',
	create_post: 'Create Post',
	will_trade_with: 'You will trade with ..',
	will_get: 'You Will Get',	
	kotuka_fee: 'Kotuka fee',
	fee_percent: '% amount that\'s converted + ',
	lets_start: 'Let\'s start the trade with registration',
	your_email: 'Your email address',
	email_address: 'Email address',
	password: 'Password',
	google: 'Google',
	facebook: 'Facebook',
	sent_confirm: 'We\'ve sent you email confirmation',
	to_log_in: 'To log in, you need to confirm your email. Check your mail',
	we_sent: 'We\'ve sent you a link to confirm your email. Simply click the link and you\'re ready.',
	cp_right: 'Copyright @ Kotuka 2018',
	need_help: 'Need Help ?',
	post: 'Post',
	transaction: 'Transaction',
	recipient: 'Recipient',
	lets_complete_your_profile: 'Let\'s complete your profile..',
	first_n_midle_name: 'First & Middle Name',
	last_name: 'Last Name',
	phone: 'Phone Number',
	birthdate: 'Birthdate',
	address: 'Address',
	you_are_trading : 'You are trading with',
	purpose : 'Purpose',
	review: 'Review',
	transfer_process: 'Transfer Process',
	cancel: 'cancel',
	add: 'add',
	edit: 'edit',
	add_new_recipient_account: 'Add new recipient account',
	bank_account: 'Bank account',
	sort_code: 'Sort Code',
	country: 'Country',
	other: 'Other',
	question: 'Question',
	send: 'Send',
	fast: 'Fast',
	tolerable: 'Tolerable',
	fair: 'Fair',
	remove: 'Remove',
	transaction_status: 'Transaction Status',
	you: 'You',
	pay_now: 'Pay Now',
	search_again: 'Search Again',
	search: 'Search',
	no_post: 'There\'s no post yet , why don\'t create your own ?',
	prev: 'Prev',
	next: 'Next',
	account_no: 'Account Number',
	description: 'Description',
	myself: 'My Self',
	someone_else: 'Someone Else',
	you_forgot: 'You Forgot your password?',
	its_oke: 'It\'s Okay, let\'s get it back. Tell us your email address and we will tell you how to retrieve your password back',
	user_example:'user@example.com',
	retrieve_password: 'Retrieve Password',
	we_sent_email_retrieve: 'We have sent you email retrieval',
	check_your_email: 'Check your email. We have sent you email to retrieve your password',
	didnt_get_email: 'Didn\'t get any email?',
	reset_password: 'Reset Password',
	your_old_password: 'Your Old Password',
	your_new_password: 'Your New Password',
	confirm_new_password: 'Confirm Your New Password',
	reset: 'Reset',
	total_transfer: 'Total Transfer',
	guaranted_rate: 'Guaranteed rate (24 hrs)',
	privacy_selection: 'Privacy Selection',
	show_my_name: 'Show my name on list',
	anon: 'Show me as anonymous',
	who_are_you_sending_money_to: 'Who are you sending money to?',
	business_charity: 'Business/Charity',
	select_bank_account: 'Select Bank Account',
	add_account: 'Add Account',	
	save: 'Save',
	what_purpose: 'What\'s your purpose of this trade?'	,
	for: 'for',
	transfer_detail: 'Transfer Detail',
	recipient_detail: 'Recipient Detail',
	amount_to_convert: 'Amount to convert',
	cancel_trade: 'Cancel Trade',
	confirm_and_continue: 'Confirm and Continue',
	transfer_mehtod: 'Transfer Method',
	select_bank: 'Select Bank',
	kotuka_acc_detail: 'Kotuka\'s Account Detail',
	to: 'To',
	time_limit: 'Time Limit',
	the_money: 'The money must sent from an acount in your name',
	have_sent_money: 'I have sent the money',
	will_send_money_later: 'I will send the money later',
	identify_verification: 'Identity Verification',
	for_security_reason: 'For security reason, we need to verify your identity. Please upload your ID-Card.',
	upload_id_card: 'Upload ID-Card',
	verify_my_identity: 'Verify My Identity',
	currency: 'Currency',
	uniq_code: 'Unique Code',
	pick: 'Pick',
	how_you_want_transfer: 'How you want to transfer your money?',
	manual_transfer: 'Manual Transfer',
	va_transfer: 'Virtual Account Transfer',
	before_we_move: 'Before we move',
	upload: 'Upload',
	complete_my_profile: 'Complete My Profile',
	profile: 'Profile',
	my_profile: 'My Profile',
	basic_information: 'Basic Information',
	contact_information: 'Contact Information',
	origin_country: 'Origin Country',
	settings: 'Settings',
	change_password: 'Change Password',
	email: 'Email',
	change: 'Change',
	edit_profile: 'Edit Profile',
	postalCode: 'Postal Code',
	login_invalid: 'Username or password invalid',
	wrong: 'Something went wrong, please try again.',
	already_click_link: 'Already click the link ?',
	relogin: 'Relogin',
	wrong_email: 'Email is not valid',
	wrong_vocal_letter: 'At least 3 characters with vocal letter',
	wrong_number: 'At least 3 number',
	wrong_select: 'Please select one options',
	wrong_postal_code: 'Postal code is not valid',
	wrong_phone: 'Phone number is not valid',
	name: 'Name',
	transfer_with: 'Transfer with',	
	success_complete_profile: 'Success! Thank you for completing your profile.',
	success_update_profile: 'Success! Thank you for updating your profile.',
	success_create_recipient: 'Success create recipient',
	success_delete_recipient: 'Success delete recipient',
	success_send_email: 'Success ! Your question has been sent',
	fail_create_post: 'Failed to create post',
	fail_update_profile: 'Failed to update profile' ,
	fail_create_recipient: 'Failed to create recipient',
	fail_delete_recipient: 'Failed to delete recipient',
	fail_send_email: 'Failed to send your question'
}

