export const SET_LOADING = 'src/containers/Transaction/SET_LOADING'
export const SET_INITIAL_STATE = 'src/containers/Transaction/SET_INITIAL_STATE'
export const IS_INQUIRY = 'src/containers/Transaction/IS_INQUIRY'
export const SET_INQUIRIES = 'src/containers/Transaction/SET_INQUIRIES'
export const SET_STATUSES = 'src/containers/Transaction/SET_STATUSES'