export const SET_LOADING = 'src/containers/Home/SET_LOADING'
export const SET_CHOOSE_NEED = 'src/containers/Home/SET_CHOOSE_NEED'
export const SET_CHOOSE_HAVE = 'src/containers/Home/SET_CHOOSE_HAVE'
export const SET_AMOUNT_NEED = 'src/containers/Home/SET_AMOUNT_NEED'
export const SET_AMOUNT_HAVE = 'src/containers/Home/SET_AMOUNT_HAVE'
export const GET_TRADES = 'src/containers/Home/GET_TRADES'
export const SET_SELECTED_TRADES = 'src/containers/Home/SET_SELECTED_TRADES'