export const SET_LOADING = 'src/containers/Header/SET_LOADING'
export const SET_INITIAL_STATE = 'src/containers/Header/SET_INITIAL_STATE'
export const SET_USER = 'src/containers/Header/SET_USER'
export const SET_ID_CARD = 'src/containers/Header/SET_ID_CARD'
export const SET_INVALID = 'src/containers/Header/SET_INVALID'